language: java
jdk:
  - openjdk11

branches:
  only:
    - master

#travis server의 홈
cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.gradle'
script: "./gradlew clean build"

#CI 실행완료시 메일로 알람
notifications:
  email:
    recipients:
      - grove156@gmail.com

#리눅스 ./gradlew 에 접급할 수 있는 권한
before_install:
  - chmod +x gradlew

before_deploy:
  - zip -r resume-manager *
  - mkdir -p deploy
  - mv resume-manager.zip deploy/resume-manager.zip
deploy:
  - provider: s3
    access_key_id: $AWS_ACCESS_KEY #트레비스 설정값
    secret_access_key: $AWS_SECRET_KEY #트래비스 설정값
    bucket: rm-build #s3 버킷이름
    region: ap-northeast-2
    skip_cleanup: true
    acl: private #zip파일 접근을 private으로
    local_dir: deploy #before_deploy에서 생성한 디렉토리
    wait-until-deployed: true