language: java
jdk:
  - openjdk11

branches:
  only:
    - master

#travis server의 홈
cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.gradle'
script: "./gradlew clean build"

#CI 실행완료시 메일로 알람
notifications:
  email:
    recipients:
      - grove156@gmail.com

#리눅스 ./gradlew 에 접급할 수 있는 권한
before_install:
  - chomod +x gradlew